#ifndef _MNVIC_CONFIG_H_
#define _MNVIC_CONFIG_H_

/*

	MNVIC_GROUP_SUB_DISTRIBUTION

 	    1- MNVIC_GROUP_4_SUB_0
		2- MNVIC_GROUP_3_SUB_1
		3- MNVIC_GROUP_2_SUB_2
		4- MNVIC_GROUP_1_SUB_3
		5- MNVIC_GROUP_0_SUB_4


 */

#define MNVIC_GROUP_SUB_DISTRIBUTION  MNVIC_GROUP_2_SUB_2

#endif
